SocksPort 9050
SocksPolicy accept 127.0.0.1
Log notice file /tmp/tor.log
DataDirectory /tmp/tor-data
HiddenServiceDir /tmp/tor-hs/eon-mesh
HiddenServicePort 80 127.0.0.1:8787
HiddenServicePort 443 127.0.0.1:8443
